"""PostgreSQL store: every scraped job, its evaluation, and your application history."""

from __future__ import annotations

import json
import threading
from contextlib import contextmanager
from datetime import UTC, datetime
from functools import lru_cache

from psycopg.conninfo import conninfo_to_dict
from psycopg_pool import ConnectionPool, PoolTimeout

from .config import DATABASE_URL, ensure_dirs
from .models import Evaluation, Job

APP_STATUSES = [
    "queued",
    "in_progress",
    "applied",
    "needs_manual",
    "failed",
    "skipped",
    "screening",
    "interviewing",
    "offer",
    "rejected",
    "withdrawn",
]

SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    source TEXT, company TEXT, title TEXT, location TEXT, url TEXT, apply_url TEXT,
    description TEXT, remote INTEGER, workplace TEXT, posted_at TEXT,
    ats TEXT, ats_slug TEXT, external_id TEXT, extra TEXT,
    first_seen TEXT, last_seen TEXT,
    -- evaluation
    region TEXT, is_wfh INTEGER, preferred_city INTEGER, visa TEXT, rating DOUBLE PRECISION,
    kw_score INTEGER, llm_score INTEGER, llm_json TEXT, score INTEGER,
    decision TEXT, reasons TEXT, evaluated_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_jobs_decision ON jobs(decision, score DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT UNIQUE REFERENCES jobs(id),
    status TEXT NOT NULL,
    method TEXT,                 -- auto | assisted | manual
    applied_at TEXT, updated_at TEXT,
    cover_letter TEXT, answers TEXT, screenshot TEXT, notes TEXT, error TEXT
);
CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER REFERENCES applications(id),
    ts TEXT, status TEXT, note TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_application ON events(application_id);
"""


def now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


class Row(tuple):
    """A result row readable by position (`r[0]`) or column name (`r["id"]`), and convertible with `dict(r)`."""

    __slots__ = ()
    _index: dict[str, int] = {}

    def __getitem__(self, key):
        if isinstance(key, str):
            return tuple.__getitem__(self, self._index[key])
        return tuple.__getitem__(self, key)

    def keys(self):
        return list(self._index)


@lru_cache(maxsize=256)
def _row_class(names: tuple[str, ...]) -> type[Row]:
    return type("Row", (Row,), {"__slots__": (), "_index": {n: i for i, n in enumerate(names)}})


def row_factory(cursor):
    return _row_class(tuple(c.name for c in cursor.description or []))


_pool: ConnectionPool | None = None
_pool_lock = threading.Lock()


def pool() -> ConnectionPool:
    """One pool per process; the schema is created the first time it opens."""
    global _pool
    with _pool_lock:
        if _pool is None:
            p = ConnectionPool(DATABASE_URL, min_size=1, max_size=10, kwargs={"row_factory": row_factory}, open=False)
            try:
                p.open(wait=True, timeout=10)
            except PoolTimeout as e:
                p.close()
                where = conninfo_to_dict(DATABASE_URL)
                raise RuntimeError(
                    f"Can't reach PostgreSQL at {where.get('host', 'localhost')}:{where.get('port', 5432)}. "
                    "Start it with `make db-up` (or set DATABASE_URL)."
                ) from e
            with p.connection() as conn:
                conn.execute(SCHEMA)
            _pool = p
        return _pool


@contextmanager
def connect():
    """A connection whose work is committed on success and rolled back on error."""
    ensure_dirs()
    with pool().connection() as conn:
        yield conn


def _text(s: str | None) -> str | None:
    """Postgres text can't hold NUL characters, which some scraped pages contain."""
    return s.replace("\x00", "") if s else s


def upsert_jobs(conn, jobs: list[Job]) -> tuple[int, int]:
    new = 0
    ts = now()
    for j in jobs:
        exists = conn.execute("SELECT 1 FROM jobs WHERE id=%s", (j.id,)).fetchone()
        row = dict(
            source=j.source,
            company=_text(j.company),
            title=_text(j.title),
            location=_text(j.location),
            url=_text(j.url),
            apply_url=_text(j.apply_url),
            description=_text(j.description),
            remote=None if j.remote is None else int(j.remote),
            workplace=j.workplace,
            posted_at=j.posted_at.isoformat() if j.posted_at else None,
            ats=j.ats,
            ats_slug=j.ats_slug,
            external_id=j.external_id,
            extra=_text(json.dumps(j.extra)),
            last_seen=ts,
        )
        if exists:
            sets = ", ".join(f"{k}=%({k})s" for k in row)
            conn.execute(f"UPDATE jobs SET {sets} WHERE id=%(id)s", {**row, "id": j.id})
        else:
            new += 1
            row.update(id=j.id, first_seen=ts)
            cols = ", ".join(row)
            vals = ", ".join(f"%({k})s" for k in row)
            conn.execute(f"INSERT INTO jobs ({cols}) VALUES ({vals})", row)
    return new, len(jobs) - new


def _aware(s: str | None) -> datetime | None:
    if not s:
        return None
    dt = datetime.fromisoformat(s)
    return dt if dt.tzinfo else dt.replace(tzinfo=UTC)


def row_to_job(r: Row) -> Job:
    return Job(
        source=r["source"],
        external_id=r["external_id"],
        company=r["company"],
        title=r["title"],
        location=r["location"] or "",
        url=r["url"],
        description=r["description"] or "",
        apply_url=r["apply_url"],
        remote=None if r["remote"] is None else bool(r["remote"]),
        workplace=r["workplace"],
        posted_at=_aware(r["posted_at"]),
        ats=r["ats"],
        ats_slug=r["ats_slug"],
        extra=json.loads(r["extra"] or "{}"),
    )


def save_evaluation(conn, job_id: str, ev: Evaluation, llm_json: str | None = None) -> None:
    conn.execute(
        """UPDATE jobs SET region=%s, is_wfh=%s, preferred_city=%s, visa=%s, rating=%s, kw_score=%s,
           llm_score=%s, llm_json=COALESCE(%s, llm_json), score=%s, decision=%s, reasons=%s, evaluated_at=%s
           WHERE id=%s""",
        (
            ev.region,
            int(ev.is_wfh),
            int(ev.preferred_city),
            ev.visa,
            ev.rating,
            ev.kw_score,
            ev.llm_score,
            llm_json,
            ev.score,
            ev.decision,
            json.dumps(ev.reasons),
            now(),
            job_id,
        ),
    )


def set_status(conn, job_id: str, status: str, note: str = "", method: str | None = None, **fields) -> int:
    if status not in APP_STATUSES:
        raise ValueError(f"status must be one of {APP_STATUSES}")
    ts = now()
    app = conn.execute("SELECT id FROM applications WHERE job_id=%s", (job_id,)).fetchone()
    if app is None:
        app_id = conn.execute(
            "INSERT INTO applications (job_id, status, method, updated_at) VALUES (%s,%s,%s,%s) RETURNING id",
            (job_id, status, method, ts),
        ).fetchone()[0]
    else:
        app_id = app["id"]
        conn.execute(
            "UPDATE applications SET status=%s, updated_at=%s, method=COALESCE(%s, method) WHERE id=%s",
            (status, ts, method, app_id),
        )
    if status == "applied":
        conn.execute("UPDATE applications SET applied_at=COALESCE(applied_at, %s) WHERE id=%s", (ts, app_id))
    for k, v in fields.items():
        if k in ("cover_letter", "answers", "screenshot", "notes", "error"):
            conn.execute(
                f"UPDATE applications SET {k}=%s WHERE id=%s",
                (json.dumps(v) if isinstance(v, (dict, list)) else v, app_id),
            )
    conn.execute(
        "INSERT INTO events (application_id, ts, status, note) VALUES (%s,%s,%s,%s)", (app_id, ts, status, note)
    )
    return app_id


def applied_today(conn) -> int:
    day = datetime.now(UTC).date().isoformat()
    return conn.execute("SELECT COUNT(*) FROM applications WHERE applied_at >= %s", (day,)).fetchone()[0]
