"""PostgreSQL store: every scraped job, its evaluation, and your application history."""

from __future__ import annotations

import json
import sqlite3
import threading
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from .config import database_conninfo, ensure_dirs
from .models import Evaluation, Job

APP_STATUSES = [
    "queued",
    "in_progress",
    "applied",
    "needs_manual",
    "failed",
    "skipped",
    "screening",
    "interviewing",
    "offer",
    "rejected",
    "withdrawn",
]
# Applications that still need action, so their jobs stay in the job lists
OPEN_STATUSES = ("queued", "needs_manual", "failed")
# Free-form application fields that set_status() may write
APPLICATION_FIELDS = ("cover_letter", "answers", "screenshot", "notes", "error")

SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    source TEXT, company TEXT, title TEXT, location TEXT, url TEXT, apply_url TEXT,
    description TEXT, remote INTEGER, workplace TEXT, posted_at TEXT,
    ats TEXT, ats_slug TEXT, external_id TEXT, extra TEXT,
    first_seen TEXT, last_seen TEXT,
    -- evaluation
    region TEXT, is_wfh INTEGER, preferred_city INTEGER, visa TEXT, rating DOUBLE PRECISION,
    kw_score INTEGER, llm_score INTEGER, llm_json TEXT, score INTEGER,
    decision TEXT, reasons TEXT, evaluated_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_jobs_decision ON jobs(decision, score DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT UNIQUE REFERENCES jobs(id),
    status TEXT NOT NULL,
    method TEXT,                 -- auto | assisted | manual
    applied_at TEXT, updated_at TEXT,
    cover_letter TEXT, answers TEXT, screenshot TEXT, notes TEXT, error TEXT
);
CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER REFERENCES applications(id),
    ts TEXT, status TEXT, note TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_application ON events(application_id);
"""


def now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def scalar(conn, query, params=None):
    """The first column of the first row (e.g. a COUNT), or None when there are no rows."""
    row = conn.execute(query, params).fetchone()
    return None if row is None else next(iter(row.values()))


def pairs(conn, query, params=None) -> dict:
    """A two-column query as {first column: second column}, e.g. `SELECT status, COUNT(*) ... GROUP BY status`."""
    return dict(tuple(r.values()) for r in conn.execute(query, params))


class DatabaseUnavailable(RuntimeError):
    """PostgreSQL can't be reached or refused the login; the message says why and what to do."""


def check_connection(conninfo: str) -> None:
    """Connect once, so a bad host/port/password surfaces as one clear error instead of pool retries."""
    try:
        psycopg.connect(conninfo, connect_timeout=5).close()
    except psycopg.OperationalError as e:
        where = conninfo_to_dict(conninfo)
        # libpq says 'connection to server at "host", port N failed: <cause>' (plus hints); keep the cause
        reason = " ".join(str(e).split()).rpartition(" failed: ")[2]
        raise DatabaseUnavailable(
            f"Can't connect to PostgreSQL at {where.get('host', 'localhost')}:{where.get('port', 5432)}: {reason}\n"
            "Is it running (`make db-up`)? Do the POSTGRES_* settings in .env match the ones the database was "
            "created with? (They only apply when it is first created.)"
        ) from None


_pool: ConnectionPool | None = None
_pool_lock = threading.Lock()


def pool() -> ConnectionPool:
    """One pool per process; the schema is created the first time it opens."""
    global _pool
    with _pool_lock:
        if _pool is None:
            conninfo = database_conninfo()
            check_connection(conninfo)
            p = ConnectionPool(conninfo, min_size=1, max_size=10, kwargs={"row_factory": dict_row}, open=False)
            p.open(wait=True, timeout=10)
            with p.connection() as conn:
                conn.execute(SCHEMA)
            _pool = p
        return _pool


@contextmanager
def connect():
    """A connection whose work is committed on success and rolled back on error."""
    ensure_dirs()
    with pool().connection() as conn:
        yield conn


def _text(s: str | None) -> str | None:
    """Postgres text can't hold NUL characters, which some scraped pages contain."""
    return s.replace("\x00", "") if s else s


_JOB_COLUMNS = (
    "id source company title location url apply_url description remote workplace posted_at "
    "ats ats_slug external_id extra first_seen last_seen"
).split()
# On conflict everything except id and first_seen is refreshed. xmax = 0 only for a freshly inserted row.
_UPSERT_JOB = sql.SQL(
    "INSERT INTO jobs ({cols}) VALUES ({vals}) ON CONFLICT (id) DO UPDATE SET {sets} "
    "RETURNING (xmax = 0)::int AS inserted"
).format(
    cols=sql.SQL(", ").join(map(sql.Identifier, _JOB_COLUMNS)),
    vals=sql.SQL(", ").join(map(sql.Placeholder, _JOB_COLUMNS)),
    sets=sql.SQL(", ").join(
        sql.SQL("{c} = EXCLUDED.{c}").format(c=sql.Identifier(c)) for c in _JOB_COLUMNS if c not in ("id", "first_seen")
    ),
)


def upsert_jobs(conn, jobs: list[Job]) -> tuple[int, int]:
    """Insert new jobs and refresh known ones; returns (new, updated)."""
    new = 0
    ts = now()
    for j in jobs:
        row = dict(
            id=j.id,
            source=j.source,
            company=_text(j.company),
            title=_text(j.title),
            location=_text(j.location),
            url=_text(j.url),
            apply_url=_text(j.apply_url),
            description=_text(j.description),
            remote=None if j.remote is None else int(j.remote),
            workplace=j.workplace,
            posted_at=j.posted_at.isoformat() if j.posted_at else None,
            ats=j.ats,
            ats_slug=j.ats_slug,
            external_id=j.external_id,
            extra=_text(json.dumps(j.extra)),
            first_seen=ts,
            last_seen=ts,
        )
        new += conn.execute(_UPSERT_JOB, row).fetchone()["inserted"]
    return new, len(jobs) - new


def _aware(s: str | None) -> datetime | None:
    if not s:
        return None
    dt = datetime.fromisoformat(s)
    return dt if dt.tzinfo else dt.replace(tzinfo=UTC)


def row_to_job(r: dict) -> Job:
    return Job(
        source=r["source"],
        external_id=r["external_id"],
        company=r["company"],
        title=r["title"],
        location=r["location"] or "",
        url=r["url"],
        description=r["description"] or "",
        apply_url=r["apply_url"],
        remote=None if r["remote"] is None else bool(r["remote"]),
        workplace=r["workplace"],
        posted_at=_aware(r["posted_at"]),
        ats=r["ats"],
        ats_slug=r["ats_slug"],
        extra=json.loads(r["extra"] or "{}"),
    )


def save_evaluation(conn, job_id: str, ev: Evaluation, llm_json: str | None = None) -> None:
    conn.execute(
        """UPDATE jobs SET region=%s, is_wfh=%s, preferred_city=%s, visa=%s, rating=%s, kw_score=%s,
           llm_score=%s, llm_json=COALESCE(%s, llm_json), score=%s, decision=%s, reasons=%s, evaluated_at=%s
           WHERE id=%s""",
        (
            ev.region,
            int(ev.is_wfh),
            int(ev.preferred_city),
            ev.visa,
            ev.rating,
            ev.kw_score,
            ev.llm_score,
            llm_json,
            ev.score,
            ev.decision,
            json.dumps(ev.reasons),
            now(),
            job_id,
        ),
    )


def set_status(conn, job_id: str, status: str, note: str = "", method: str | None = None, **fields) -> int:
    if status not in APP_STATUSES:
        raise ValueError(f"status must be one of {APP_STATUSES}")
    ts = now()
    app = conn.execute("SELECT id FROM applications WHERE job_id=%s", (job_id,)).fetchone()
    if app is None:
        app_id = conn.execute(
            "INSERT INTO applications (job_id, status, method, updated_at) VALUES (%s,%s,%s,%s) RETURNING id",
            (job_id, status, method, ts),
        ).fetchone()["id"]
    else:
        app_id = app["id"]
        conn.execute(
            "UPDATE applications SET status=%s, updated_at=%s, method=COALESCE(%s, method) WHERE id=%s",
            (status, ts, method, app_id),
        )
    if status == "applied":
        conn.execute("UPDATE applications SET applied_at=COALESCE(applied_at, %s) WHERE id=%s", (ts, app_id))
    values = {k: json.dumps(v) if isinstance(v, (dict, list)) else v for k, v in fields.items()}
    if unknown := values.keys() - set(APPLICATION_FIELDS):
        raise ValueError(f"unknown application fields: {sorted(unknown)}")
    if values:
        sets = sql.SQL(", ").join(sql.SQL("{} = %s").format(sql.Identifier(k)) for k in values)
        conn.execute(sql.SQL("UPDATE applications SET {} WHERE id = %s").format(sets), (*values.values(), app_id))
    conn.execute(
        "INSERT INTO events (application_id, ts, status, note) VALUES (%s,%s,%s,%s)", (app_id, ts, status, note)
    )
    return app_id


def applied_today(conn) -> int:
    day = datetime.now(UTC).date().isoformat()
    return scalar(conn, "SELECT COUNT(*) FROM applications WHERE applied_at >= %s", (day,))


# ---------------------------------------------------------------- one-off import from the SQLite version

IMPORT_TABLES = ("jobs", "applications", "events")  # parents before children (foreign keys)


def _columns(conn, table: str) -> set[str]:
    cur = conn.execute(sql.SQL("SELECT * FROM {} LIMIT 0").format(sql.Identifier(table)))
    return {c.name for c in cur.description}


def import_sqlite(conn, path) -> dict[str, int]:
    """Copy rows from the old SQLite database; rows already present are skipped. Returns rows read per table.

    Only columns that exist in both databases are copied, and identifiers are quoted by psycopg, so a
    tampered SQLite file can't inject SQL through its column names.
    """
    src = sqlite3.connect(f"{Path(path).resolve().as_uri()}?mode=ro", uri=True)  # never modify the old file
    try:
        counts = {}
        for table in IMPORT_TABLES:
            src_cols = [r[0] for r in src.execute("SELECT name FROM pragma_table_info(?)", (table,))]
            pg_cols = _columns(conn, table)
            cols = [c for c in src_cols if c in pg_cols]  # names from our own schema, so safe to quote below
            quoted = ", ".join(f'"{c}"' for c in cols)
            rows = src.execute(f'SELECT {quoted} FROM "{table}"').fetchall() if cols else []
            counts[table] = len(rows)
            if not rows:
                continue
            insert = sql.SQL("INSERT INTO {t} ({cols}) VALUES ({vals}) ON CONFLICT DO NOTHING").format(
                t=sql.Identifier(table),
                cols=sql.SQL(", ").join(map(sql.Identifier, cols)),
                vals=sql.SQL(", ").join(sql.Placeholder() * len(cols)),
            )
            with conn.cursor() as cur:
                cur.executemany(insert, [tuple(_text(v) if isinstance(v, str) else v for v in r) for r in rows])
            if "id" in cols and table != "jobs":  # move the identity past the copied ids
                conn.execute(
                    sql.SQL("SELECT setval(pg_get_serial_sequence(%s, 'id'), (SELECT MAX(id) FROM {}))").format(
                        sql.Identifier(table)
                    ),
                    (table,),
                )
        return counts
    finally:
        src.close()
